// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9q5R9hDpivPAwxP5HdQl2jwPw6d4w-NI',
    appId: '1:947085150136:web:2a7cf30737ede30bfeb14d',
    messagingSenderId: '947085150136',
    projectId: 'cv-manager-1a6ae',
    authDomain: 'cv-manager-1a6ae.firebaseapp.com',
    storageBucket: 'cv-manager-1a6ae.firebasestorage.app',
    measurementId: 'G-LDHVCV12RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsH4iRhHQjsyumRZIf-SRPonVL1QiFBIs',
    appId: '1:947085150136:android:0a09ff84077cffdffeb14d',
    messagingSenderId: '947085150136',
    projectId: 'cv-manager-1a6ae',
    storageBucket: 'cv-manager-1a6ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7E6zkCGOMObr5ukp2N6iZkDFRnhLpeXs',
    appId: '1:947085150136:ios:2553c91eda130822feb14d',
    messagingSenderId: '947085150136',
    projectId: 'cv-manager-1a6ae',
    storageBucket: 'cv-manager-1a6ae.firebasestorage.app',
    iosBundleId: 'com.example.cvManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7E6zkCGOMObr5ukp2N6iZkDFRnhLpeXs',
    appId: '1:947085150136:ios:2553c91eda130822feb14d',
    messagingSenderId: '947085150136',
    projectId: 'cv-manager-1a6ae',
    storageBucket: 'cv-manager-1a6ae.firebasestorage.app',
    iosBundleId: 'com.example.cvManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9q5R9hDpivPAwxP5HdQl2jwPw6d4w-NI',
    appId: '1:947085150136:web:530efb11859da732feb14d',
    messagingSenderId: '947085150136',
    projectId: 'cv-manager-1a6ae',
    authDomain: 'cv-manager-1a6ae.firebaseapp.com',
    storageBucket: 'cv-manager-1a6ae.firebasestorage.app',
    measurementId: 'G-VNQZR4PF4J',
  );
}
